################################################################
### Quiz from repository: m02-small-world-erfiolkoski-beep
################################################################
[[questions]]
question = "How many edges does a node with one loop have?"
answer = "Two"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."



################################################################
### Quiz from repository: m02-small-world-amahury
################################################################
[[questions]]
question = "True or False (justify briefly): The simple cycle graph C_N with N ≥ 5 is small-world (σ > 1) under the Humphries–Gurney definition when using C as transitivity and an Erdős–Rényi baseline with the same N and M."
answer = "False. C_N has no triangles, so C = 0. With an ER baseline (same N, M) we have C_rand > 0 and L/L_rand is finite, hence σ = (0/C_rand)/(L/L_rand) = 0 < 1."

[[questions]]
question = "Consider the star graph S_N (one hub connected to N−1 leaves) with N ≥ 4. Using the Humphries–Gurney small-world coefficient σ = (C/C_rand)/(L/L_rand) with C defined as transitivity and an Erdős–Rényi baseline matching N and M, is σ > 1, σ = 1, or σ < 1? Answer with exactly one of {>, =, <} and justify briefly."
answer = "<. A star has C = 0 (no triangles) while the ER baseline has C_rand > 0 for the same N and M; L/L_rand is finite, so σ = 0 < 1."



################################################################
### Quiz from repository: m02-small-world-Onyebuchi-Iwegbu
################################################################
[[questions]]
question = "If a network has very low clustering coefficient, can it have small-world properties?"
answer = "No, a network cannot have small-world properties with very low clustering coefficient because Small-world networks are characterized by high clustering that is much higher than random and short path lengths. A network with low clustering and short paths is characterized as a random network while the network with high clustering relative to random networks is a necessary condition for small-world classification."

[[questions]]
question = "In the Watts-Strogatz model, what is the relationship between clustering coefficient and the rewiring probability especially when it increases from 0 to 1?"
answer = "The clustering coefficient would decrease monotonically from its maximum value, say when p=0 to the value of a random graph, say when p=1. It does not increase at any point during this transition - thus it has indirect relationship."


################################################################
### Quiz from repository: m02-small-world-pajarito95
################################################################
[[questions]]
question = "Given an initial, potentially small-world network, how would you describe the approach for normalization in order to calculate it's small-world coefficient? Answer with less than 50 words."
answer = "Consider the type of degree distribution of the network and whether there is anything you want to preserve or account for (e.g. communities, degree sequence). Then you may determine which random model to use for normalization."

[[questions]]
question = " What can we conclude about the small world-ness of a network where it's average clustering coefficient and global clustering coefficient are both equal to 1?"
answer = " We conclude it is not a small world network since having both coefficients equal to 1 signifies a fully connected network which therefore cannot also be small-world."



################################################################
### Quiz from repository: m02-small-world-Hemiiee
################################################################
[[questions]]
question = "The global coefficient is based on the ration between the number of triangles divided by the total number of triplets (open + close). True or False."
answer = "True!"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."



################################################################
### Quiz from repository: small-world-skojaku
################################################################
[[questions]]
question = "The global coefficient is based on the ration between the number of triangles divided by the total number of triplets (open + close). True or False."
answer = "True!"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."



################################################################
### Quiz from repository: m02-small-world-themnvrao76
################################################################
[[questions]]
question = "The global coefficient is based on the ration between the number of triangles divided by the total number of triplets (open + close). True or False."
answer = "True!"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."



################################################################
### Quiz from repository: m02-small-world-PranshUwU
################################################################
[[questions]]
question = "The global coefficient is based on the ration between the number of triangles divided by the total number of triplets (open + close). True or False."
answer = "True!"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."



################################################################
### Quiz from repository: m02-small-world-Ron573
################################################################
[[questions]]
question = "The global coefficient is based on the ration between the number of triangles divided by the total number of triplets (open + close). True or False."
answer = "True!"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."



################################################################
### Quiz from repository: m02-small-world-nedachocolate63
################################################################
[[questions]]
question = "Consider the undirected simple graph on 4 nodes with edges (0,1), (1,2), (2,0), (2,3). Using C_global = (3 × number_of_triangles) / (number_of_connected_triples), what is the global clustering coefficient?"
answer = "0.6 (There is exactly 1 triangle. Degrees are [2,2,3,1], so connected triples = C(2,2)+C(2,2)+C(3,2)+C(1,2) = 1+1+3+0 = 5. Hence C_global = 3×1 / 5 = 0.6.)"

[[questions]]
question = "For an Erdős–Rényi random graph G(n, p) with n = 1000 and expected average degree k̄ = 10 (so p = k̄/(n−1)), using the standard large-n approximations, what are the expected clustering coefficient C_rand and average path length L_rand?"
answer = "C_rand ≈ p = 10/999 ≈ 0.01001, and L_rand ≈ ln(n)/ln(k̄) = ln(1000)/ln(10) ≈ 3.0."



################################################################
### Quiz from repository: m02-small-world-usukharamwal
################################################################
[[questions]]
question = "Do Erdős–Rényi random graphs show the small-world property?"
answer = "Path lengths are short, but clustering is too low, not small-world."

[[questions]]
question = "Can a network with clustering coefficient = 1 be small-world?"
answer = "No, that’s just a complete graph (shortest path length = 1, but trivial)."



################################################################
### Quiz from repository: m02-small-world-sbi2-glitch
################################################################
[[questions]]
question = "In the Watts–Strogatz model, small-worldness emerges at all values of the rewiring probability between 0 and 1. True or False?"
answer = "False. Only in the intermediate regime."

[[questions]]
question = "Every graph with short average path length and nonzero clustering is a small-world network. True or False?"
answer = "False."



