---
title: "Welcome to SSIE 641 Advanced Topics on Network Science"
---


``Don't think! Feeeeeel'' is a famous quote by Bruce Lee in the movie *Enter the Dragon*, and this is my guiding philosophy of learning.

This course is designed to help you *feel* the concepts and tools of network science through pen-and-paper exercises and hands-on coding.

## List of Exercises and Assignments

| Module | Pen and Paper Exercise | Assignment | Slides |
|--------|------------------------|------------------|------------------|
| M01: Euler Tour | [The Koningsberg Bridge](http://estebanmoro.org/pdf/netsci_for_kids/the_konisberg_bridges.pdf) | - | [Slides](https://github.com/skojaku/adv-net-sci/tree/main/docs/slide/m01) |
| M02: Small World | [It’s a small world!! 6 degrees of separation](http://estebanmoro.org/pdf/netsci_for_kids/6_degrees_of_separation.pdf) | [Exercise](https://github.com/skojaku/adv-net-sci/blob/main/notebooks/m02-small-world/starter.ipynb) | [Slides](https://skojaku.github.io/adv-net-sci/assets/slides/m02/slide02.html) |
| M03: Robustness | [Build it, Break it, and Build it back!](m03-robustness/pen-and-paper/exercise.pdf) | [Exercise](https://github.com/skojaku/adv-net-sci/blob/main/notebooks/m03-robustness/exercise.ipynb) | [Slides](https://skojaku.github.io/adv-net-sci/assets/slides/m03/slide03.html) |
| M04: Friendship Paradox | [Data Visualization](m04-friendship-paradox/pen-and-paper/exercise.pdf) | [Exercise](https://github.com/skojaku/adv-net-sci/blob/main/notebooks/m04-friendship-paradox/exercise.ipynb) | [Slides](https://skojaku.github.io/adv-net-sci/assets/slides/m04/slide04.html) |
| M05: Clustering | [Perfect vs. Almost Perfect](m05-clustering/pen-and-paper/exercise.pdf) | [Community detection](https://github.com/skojaku/adv-net-sci/blob/main/notebooks/m05-clustering/exercise-m05-clustering.ipynb) | [Slides](https://skojaku.github.io/adv-net-sci/assets/slides/m05/slide05.html) |
| M06: Centrality | [Who's the Big Cheese in the University Clubs?](m06-centrality/pen-and-paper/exercise.pdf) | [Roads to Rome](https://github.com/skojaku/adv-net-sci/blob/main/notebooks/m06-centrality/exercise-m06-centrality.ipynb) | [Slides](https://github.com/skojaku/adv-net-sci/tree/main/docs/slide/m06) |
| M07: Random Walks | [Random Walks on Networks](m07-random-walks/pen-and-paper/exercise.pdf) | - | [Slides](https://skojaku.github.io/adv-net-sci/assets/slides/m07/slide07.html) |
| M08: Embedding | [Network Embeddings](m08-embedding/pen-and-paper/exercise.pdf) | - | [Slides](https://skojaku.github.io/adv-net-sci/assets/slides/m08/slide08.html) |
| M09: Graph Neural Networks | [Graph Neural Networks](m09-graph-neural-networks/pen-and-paper/exercise.pdf) | - | [Slides](https://github.com/skojaku/adv-net-sci/tree/main/docs/slide/m09) |
