# /// script
# requires-python = ">=3.10,<3.14"
# dependencies = ["networkx", "numpy", "scikit-learn", "scipy"]
# ///
"""Writes src/data/*.ts, the precomputed data the slides read.

    uv run slides/m05/remotion/scripts/make_data.py

Everything here is also asserted in verify_numbers.py. Positions are in the unit box [0, 1] x [0, 1]
(the slide maps them onto its own region), so a layout is chosen for how it looks in a box of
about 900 x 760 px: no two discs closer than 1.3 disc diameters at 46px discs.
"""

import json
import math
from pathlib import Path

import networkx as nx
import numpy as np
from sklearn.metrics import adjusted_rand_score as ARI
from sklearn.metrics import rand_score as RAND

OUT = Path(__file__).resolve().parent.parent / "src" / "data"
OUT.mkdir(parents=True, exist_ok=True)
Q = lambda g, parts: nx.community.modularity(g, parts, weight=None)


def ts(name, value, doc=""):
    body = json.dumps(value)
    return (f"/** {doc} */\n" if doc else "") + f"export const {name} = {body} as const;\n\n"


def unit_layout(g, seed, box=(900, 760), disc=46, tries=400, kind="kk", dmin=60):
    """A layout in [0,1]^2 whose discs do not crowd in the given pixel box."""
    best = None
    for s in range(seed, seed + tries):
        pos = nx.kamada_kawai_layout(g) if kind == "kk" else nx.spring_layout(g, seed=s, iterations=300, k=1.6 / math.sqrt(len(g)))
        xs = np.array([pos[v][0] for v in sorted(g)])
        ys = np.array([pos[v][1] for v in sorted(g)])
        xs = (xs - xs.min()) / (xs.max() - xs.min())
        ys = (ys - ys.min()) / (ys.max() - ys.min())
        px = np.stack([xs * box[0], ys * box[1]], 1)
        # push apart any two discs closer than dmin, keeping everything inside the box
        for _ in range(500):
            moved = False
            for i in range(len(px)):
                for j in range(i):
                    v = px[i] - px[j]
                    dist = np.linalg.norm(v)
                    if dist < dmin:
                        v = v / (dist or 1e-6) if dist else np.array([1.0, 0.0])
                        px[i] += v * (dmin - dist) / 2
                        px[j] -= v * (dmin - dist) / 2
                        moved = True
            px[:, 0] = np.clip(px[:, 0], 0, box[0])
            px[:, 1] = np.clip(px[:, 1], 0, box[1])
            if not moved:
                break
        xs, ys = px[:, 0] / box[0], px[:, 1] / box[1]
        d = min(np.linalg.norm(px[i] - px[j]) for i in range(len(px)) for j in range(i))
        if best is None or d > best[0]:
            best = (d, xs, ys)
        if kind == "kk":
            break
    d, xs, ys = best
    return d, [[round(float(x), 4), round(float(y), 4)] for x, y in zip(xs, ys)]


out = "// Generated by scripts/make_data.py. Do not edit by hand.\n\n"

# ------------------------------------------------------------------ karate club
w = nx.karate_club_graph()
g = nx.Graph()
g.add_nodes_from(range(34))
g.add_edges_from(w.edges())
real = [0 if w.nodes[v]["club"] == "Mr. Hi" else 1 for v in w]
FOUR = [[0, 1, 2, 3, 7, 11, 12, 13, 17, 19, 21], [4, 5, 6, 10, 16],
        [8, 9, 14, 15, 18, 20, 22, 30, 32, 33], [23, 24, 25, 26, 27, 28, 29, 31]]
THREE = [[0, 1, 2, 3, 7, 9, 11, 12, 13, 17, 19, 21], [4, 5, 6, 10, 16],
         [8, 14, 15, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]]


def lab(parts):
    o = [0] * 34
    for i, p in enumerate(parts):
        for v in p:
            o[v] = i
    return o


d, kpos = unit_layout(g, 0)
print("karate layout min disc distance in a 900x760 box: %.1f px" % d)
res = {}
for seed in range(400):
    p = nx.community.louvain_communities(g, seed=seed, weight=None)
    key = tuple(sorted(tuple(sorted(c)) for c in p))
    res.setdefault(key, [Q(g, p), 0])
    res[key][1] += 1
lq = sorted(v[0] for v in res.values())
assert len(lq) == 16
out += ts("KARATE_POS", kpos, "34 nodes, unit box, Kamada-Kawai.")
out += ts("KARATE_EDGES", [list(e) for e in g.edges()], "78 edges, unweighted.")
out += ts("KARATE_REAL", real, "Zachary's split: 0 = Mr. Hi, 1 = Officer. 17 and 17.")
out += ts("KARATE_FOUR", lab(FOUR), "Group of each node: 4 groups, Q = 0.407.")
out += ts("KARATE_THREE", lab(THREE), "Group of each node: 3 groups, Q = 0.402.")
out += ts("KARATE_LOUVAIN_Q", [round(x, 4) for x in lq], "Q of the 16 distinct splits Louvain returns in 400 seeds.")

# ------------------------------------------------------------------ the random network of S06 and S07
r0 = nx.gnm_random_graph(34, 78, seed=0)
levels = list(nx.community.louvain_partitions(r0, seed=1))
final = levels[-1]
assert len(final) == 5 and abs(Q(r0, final) - 0.346) < 5e-4
d0, rpos = unit_layout(r0, 0, kind="spring")
print("noise layout min disc distance: %.1f px" % d0)
labs = []
for part in levels:
    labs.append(lab([sorted(c) for c in part]) if len(part) > 1 else [0] * 34)
# levels of Louvain: first the groups after the local moves, then after aggregation. Prepend singletons.
out += ts("NOISE_POS", rpos, "34 nodes of G(34, 78), seed 0, unit box.")
out += ts("NOISE_EDGES", [list(e) for e in r0.edges()], "78 edges of G(34, 78), seed 0.")
out += ts("NOISE_LEVELS", labs, "Louvain (seed 1) group of each node after each level; the last is the final 5 groups, Q = 0.346.")


def best_q(r):
    return max(Q(r, nx.community.louvain_communities(r, seed=k)) for k in range(5))


n34 = [best_q(nx.gnm_random_graph(34, 78, seed=s)) for s in range(200)]
n100 = [max(Q(r, nx.community.louvain_communities(r, seed=k)) for k in range(3))
        for r in (nx.gnp_random_graph(100, 0.05, seed=s) for s in range(100))]
out += ts("NOISE34_Q", [round(x, 4) for x in n34], "Louvain Q on 200 random networks of 34 nodes, 78 edges.")
out += ts("NOISE100_Q", [round(x, 4) for x in n100], "Louvain Q on 100 random networks of 100 nodes, p = 0.05.")

# ------------------------------------------------------------------ 30 dots, 5 groups of 6, shuffled
x = np.repeat(np.arange(5), 6)
rng = np.random.default_rng(0)
shuf, rr, aa = [], [], []
for _ in range(40):
    y = rng.permutation(x)
    shuf.append([int(v) for v in y])
    rr.append(round(float(RAND(x, y)), 4))
    aa.append(round(float(ARI(x, y)), 4))
ea = 75 * 75 / 435
out += ts("SHUFFLES", shuf, "40 random relabelings of 30 dots (5 groups of 6, same sizes).")
out += ts("SHUFFLE_RAND", rr, "Rand index of each shuffle against the true groups.")
out += ts("SHUFFLE_ARI", aa, "Adjusted Rand index of each shuffle.")
out += ts("EXPECTED_RAND", round((435 + 2 * ea - 150) / 435, 4), "Expected Rand index of a random relabeling: 0.7146.")

# ------------------------------------------------------------------ SBM, 8 nodes
u = np.random.default_rng(901).random(28)
out += ts("SBM_U", [round(float(v), 6) for v in u],
          "One uniform number per pair, in the order (0,1) (0,2) ... (6,7). An edge exists when u < p of the pair's block.")
out += ts("SBM_SHUFFLE", [1, 4, 3, 5, 7, 0, 2, 6], "A fixed order of the 8 nodes (slot -> node) for the unsorted adjacency matrix; chosen so that no two neighbouring slots are joined by many edges, i.e. the blocks are not visible.")

(OUT / "data.ts").write_text(out)
print("wrote", OUT / "data.ts", len(out), "bytes")
